//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileIndexer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathToTextFileCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PathToTextFileCollection()
        {
            this.TextFiles = new HashSet<TextFile>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual PathToTextFileCollection Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextFile> TextFiles { get; set; }
    }
}
