//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileIndexer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TextFile()
        {
            this.Words = new HashSet<Words>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PathId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Words> Words { get; set; }
        public virtual PathToTextFileCollection Path { get; set; }
    }
}
